import javascriptGenerator from '../javascriptGenerator';

class Compiler {
    constructor(workspace) {
        this.workspace = workspace;

        this.characters = [
            {
                name: "Apple",
                startCostume: "_hordcoded_apple",
                position: {
                    x: 320,
                    y: 180
                },
                size: 100,
                angle: 0
            }
        ];
        this.images = [
            {
                name: "_hordcoded_apple",
                image: "https://kaboomjs.com/sprites/apple.png"
            }
        ];
        this.sounds = [];
    }

    setCharacters(array) {
        this.characters = array;
    }
    setImages(array) {
        this.images = array;
    }
    setSounds(array) {
        this.sounds = array;
    }

    /**
     * Generates code from the workspace and any set images and sounds.
     */
    compile() {
        const genCode = [javascriptGenerator.workspaceToCode(this.workspace)];
        const headerCode = [
            `/* THIS CODE WAS GENERATED BY CLAMP / BLOCKLY. IT IS NOT INTENDED TO BE READ BY HUMANS IN ITS FULL FORM. */`,
            `// Comments may still appear as they are useful internally.`,
            `const variables = {}; // all variables are stored here instead of a "const variable = 123" for each set block`,
            `// this is so we dont end up with a Scratch for Discord where setting a variable with the name "message" breaks everything`,
            `// im allowed to say that because i worked on S4D lolol`,
            `(async function() {`
        ];
        const setupCode = [
            `const characters = {}; // object so we can use invalid characters for character names and still easily access them`
        ];
        const footerCode = [
            `})();`
        ];

        // initialize images
        this.images.forEach(image => {
            const variableName = JSON.stringify(image.name);
            const variableImage = JSON.stringify(image.image);

            setupCode.push(`await Kaboom.loadSprite(${variableName}, ${variableImage});`);
        });
        // initialize sounds
        this.sounds.forEach(sound => {
            const variableName = JSON.stringify(sound.name);
            const variableData = JSON.stringify(sound.data);

            setupCode.push(`await Kaboom.loadSound(${variableName}, ${variableData});`);
        });
        // initialize character code
        this.characters.forEach(character => {
            // we need to clean all of these names to ensure they dont generate invalid code
            // so we use things like Number() and JSON.stringify() everywhere
            const variableName = JSON.stringify(character.name);

            const characterData = {
                defaultLook: JSON.stringify(character.startCostume),
                x: isNaN(Number(character.position.x)) ? 0 : Number(character.position.x),
                y: isNaN(Number(character.position.y)) ? 0 : Number(character.position.y),
                size: isNaN(Number(character.size)) ? 0 : Number(character.size),
                angle: isNaN(Number(character.angle)) ? 0 : Number(character.angle),
            };
            setupCode.push(`characters[${variableName}] = Kaboom.add([
                Kaboom.sprite(${characterData.defaultLook}),
                Kaboom.pos(${characterData.x}, ${characterData.y}),
                Kaboom.scale(${characterData.size}),
                Kaboom.rotate(${characterData.angle}),
            ]);`);
        });

        return [].concat(headerCode, setupCode, ['/* ok enough baby stuff LETS RUN SOME CODE */'], genCode, footerCode).join('\n');
    }
}

export default Compiler;