import { javascriptGenerator } from "blockly/javascript";

class Compiler {
    constructor(workspace) {
        this.workspace = workspace;
    }

    compile() {
        const genCode = [javascriptGenerator.workspaceToCode(this.workspace)];
        const headerCode = [
            `/* THIS CODE WAS GENERATED BY CLAMP / BLOCKLY. IT IS NOT INTENDED TO BE READ BY HUMANS IN ITS FULL FORM. */`,
            `(async function() {`
        ];
        const footerCode = [
            `})();`
        ];
        return [].concat(headerCode, genCode, footerCode).join('\n');
    }
}

export default Compiler;